# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: "https://github.com/pre-commit/pre-commit-hooks"
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  # Contains shared Python hooks for all services.
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: debug-statements
        language_version: python3.12
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version
    rev: v0.16.1
    hooks:
      # Linter (replaces Flake8, isort, etc.)
      - id: ruff
      # Formatter (replaces Black)
      - id: ruff-format
